### ISSUE TITLE
Extract the x-axis data (wavelength) from captured spectrum

### ISSUE THREAD

**Issue by ankur92** [sliakat/SpeReadPy#14]
Hi @sliakat, 

Thanks for uploading the example scripts on LF Automation. We have a PI Spectrometer in the lab and, currently working on automating the data collection using Python. I have a couple of questions regarding the recorded spectrum and how to parse the data from the LF application to python

(1) Which experiment method should I be using between `experiment.Acquire()` and `experiment.Capture(1)` to record a spectrum? `Acquire()` returns nothing but displays the spectrum on the application, `Capture` returns a dataset but doesn't display the captured spectrum. 
(2) I can extract the counts on each pixel in a given ROI, but I am not sure if there is a way to extract the x-axis (wavelength) of the recorded spectrum. Do you have any suggestions? 

Looking forward to hearing from you.

**Comment by sliakat** [comment]
Hi Ankur,

The wavelength calibration can be extracted from Experiment.SystemColumnCalibration or read directly from the spe file. To apply to an ROI, you'd want to take the x position of the ROI and use the slice x:width on the calibration extracted from automation / spe.

The difference between Acquire and Capture is explained in one of my tutorials in the Python automation folder (https://github.com/sliakat/SpeReadPy/tree/main/LFAutomation/PythonWebinar). Acquire() is asynchronous and returns immediately after asking LightField to acquire data and generate an spe file. Capture(n) holds the data in memory -- the LightField viewer does not see / display this data.

**Comment by ankur92** [comment]
Hi @sliakat, 

Thank you so much for your message. 

I think it would be great to add an example script which configures the spectrometer and collects a spectrum from the camera.
