### ISSUE TITLE
dll import

### ISSUE THREAD

**Issue by julienGautier77** [sliakat/SpeReadPy#15]
Hi
I try to use picam library on win 10 64 bits with python using vscode and miniconda
I had  already done it 1 or 2 years ago on another computer(but it crashed) but now i dind't succes to load the library
I had tried:
 ctypes.cdll.LoadLibrary(path to lib)
or ctypes.Winll.LoadLibrary(path to lib)
or ctypes.WinDLL(path to lib)
and I have the following error :
 FileNotFoundError: Could not find module ''C:\Program Files\Princeton Instruments\PICam\Runtime\Picam.dll' (or one of its dependencies). Try using the full path with constructor syntax.
The .dll exist and also the dependencies 
 Piac.dll
    Pida.dll
    Pidi.dll
    Picc.dll
and in System32  the dependecies also exist:
    MSVCP100.dll
    MSVCR100.dll
    KERNEL32.dll
    SHELL32.dll
    ole32.dll
Picam root is set in the environment variable
and path is also set
Do you have any suggestions
Thanks in advance

**Comment by sliakat** [comment]
Hi Julien,
I would say run the installer on the machine you get an error: https://cdn.princetoninstruments.com/picam/picam%20install.exe
It is likely you are missing other dependencies, such as Pleora and PVCam. This is a common issue that happens when trying to copy the Picam library files over (I am not sure if that's what you did, but we see it a lot) -- the installer puts other needed libraries and paths on the system.

**Comment by julienGautier77** [comment]
hi
Thanks for your answer
I have ran the installer
I try to uninstall it and run again the installer with your link but I have the same issue
FileNotFoundError: Could not find module 'C:\Users\UPX\Desktop\python\PICam\dll\Runtime\Picam.dll' (or one of its dependencies). Try using the full path with constructor syntax.

I also try to install all the Microsoft Visual C++ Redistributable ( 2005 2008 2010 2012 2013 2015-2022)

Thanks again
Julien


[cid:fd0f1ff1-0304-4316-8c4d-6676c6cd88ff][cid:36a81f24-5f90-4a8f-a304-0bc21dec1865]


Julien GAUTIER

Ingénieur de recherche

Téléphone : 01 69 31 98 31

________________________________

ENSTA Paris | Institut Polytechnique de Paris

828 boulevard des Maréchaux

91120 Palaiseau [plan<https://www.ensta-paris.fr/fr/acces-et-contacts>]

www.ensta-paris.fr<https://www.ensta-paris.fr> | LinkedIn<https://www.linkedin.com/school/ensta-paris/> | Twitter<https://www.twitter.com/ENSTAParis> | Facebook<https://www.facebook.com/ENSTA.Paris> | Instagram<https://www.instagram.com/enstaparis/>

[raison-d-etre-ensta-paris] <https://www.ensta-paris.fr/fr/raison-d-etre-ensta-paris>
________________________________
De : sliakat ***@***.***>
Envoyé : mercredi 12 juillet 2023 08:18
À : sliakat/SpeReadPy ***@***.***>
Cc : Julien GAUTIER ***@***.***>; Author ***@***.***>
Objet : Re: [sliakat/SpeReadPy] dll import (Issue #15)


Hi Julien,
I would say run the installer on the machine you get an error: https://cdn.princetoninstruments.com/picam/picam%20install.exe
It is likely you are missing other dependencies, such as Pleora and PVCam. This is a common issue that happens when trying to copy the Picam library files over (I am not sure if that's what you did, but we see it a lot) -- the installer puts other needed libraries and paths on the system.

**Comment by julienGautier77** [comment]
Hi
I think if found a solution it is certainly due to python 3.8 (see https://syntaxbug.com/ea75a69575/)
Just remplace the line  by self.picamLib = ctypes.CDLL(pathToLib, winmode=0)  or ctypes.WINDLL(pathToLib, winmode=0) 
and no more error 😃
Thanks again

**Comment by sliakat** [comment]
Thanks for the update! This is interesting because I have used Python 3.8 in the past and not encountered the issue. However, now I am using 3.11 and would prefer not to roll back.

I am glad it is working for you, and this will certainly help others in the future. Thanks again!
