### ISSUE TITLE
Quadro camera

### ISSUE THREAD

**Issue by julienGautier77** [sliakat/SpeReadPy#16]
Hi
I now try to use a Quadro camera on win 10 with picam.py
Quadro is well recognized by windows but I can not connect to the cam via pycam : 
getAvaibleCameras return the model 102 the good one
sensor name :  'Kodak 2048 x 2084 (Kaf 4320) (F)(MP)
serial number :  '0000000000' 
But when I try OpenFirstCamera
picamLib_Picam_OpenFirstCamera return the error 4 (>0) and open the demo camera
Do you think it is due to the firmware of the camera ? Perhaps it is too old to be compatile with Picam 5.xx
We also have problem to connect the camera to LightField
Thanks in advance

**Comment by sliakat** [comment]
Hi Julien,
The QuadRO is no longer a Teledyne supported camera model, and it is been known to have quirks with Windows 10. Some users have had success with this driver: https://transfereast.teledyne.com/link/3FFX07NZuAfE4Gh7TxKCSK

Try it out and see if it works for you, thanks.

**Comment by sliakat** [comment]
closing as it's been over a month.
